### ISSUE TITLE
HSM Components objects are missing

### ISSUE THREAD

**Issue by danikoala** [messagebird/php-rest-api#121]
How can I send a Media Template using the PHP SDK. As the HSM Components and Components/Parameters are missing, I don't know how to do it with the existing classes.

Do you have an example? Do I have to use plain curl?

Thank you very much.

**Comment by marcelcorso** [comment]
Hey @danikoala. We got an example for you in the repo:

https://github.com/messagebird/php-rest-api/blob/e88aea01a6975abfb08c70baba3ee3a1e4ef2916/examples/conversations/create-hsm.php

is this what you were looking for?

**Comment by danikoala** [comment]
Hi @marcelcorso!

I'm afraid it's not what I'm looking for. I already saw that example, but it doesn't have the piece of code to send media HSM (template message with files attached).

**Comment by marcelcorso** [comment]
Hey @danikoala. You are right. Right now the SDK doesn't expose the [HSMContent type](https://developers.messagebird.com/api/conversations/#hsmcontent) and the types it uses. 

But because of php's dynamic nature you can implement them yourself by looking at the docs. Implement a class (or even an array) that has all the properties described on the docs, be sure it's `jsonSerialize`able and pass that as the `content` attribute of the conversation message. 

https://github.com/messagebird/php-rest-api/blob/86b696078e81e71977922b7deb068d5a1ee28e64/src/MessageBird/Objects/Conversation/Message.php#L72

I'm sorry this is not easier. I hope you are successful (trying this is better than reimplementing everything with curl again) please consider submitting a PR to improve the sdk.

**Comment by danikoala** [comment]
Ok! Marcel, I will try and I'll back to you with some piece of code (I presume). :-)

**Comment by CoolGoose** [comment]
@danikoala we are considering this going forward. Let us know if you need any more help
