### ISSUE TITLE
Can't look up contact by msisdn

### ISSUE THREAD

**Issue by joelzerner** [messagebird/php-rest-api#123]
Although the MessageBird docs state it is possible to read a contact using the msisdn instead of the contact ID, I've been unable to achieve this using this PHP api. It won't allow me to input a number with a '+' symbol in it and returns an unspecified error.

For API Reference, see: https://developers.messagebird.com/api/contacts/#view-a-contact

Also see this issue on the nodejs wrapper: https://github.com/messagebird/messagebird-nodejs/issues/32

**Comment by modprobe** [comment]
Hi @joelzerner! Thanks for flagging this.

Unfortunately, it turns out that the documentation is actually confusing/mixed up here. It is not possible to fetch a single contact by MSISDN, as the MSISDN doesn't have to be unique for your contacts. 

It is however possible to search for contacts by MSISDN. You can use the following code to do so:

```php

$client = new \MessageBird\Client('YOUR_ACCESS_KEY');
$contacts = $client->contacts->getList(['msisdn' => 61412345678]);

var_dump($contacts->items);
```

Please make sure to format your MSISDN as digits only.

I will flag the issue with the documentation internally and we will make sure to clear it up!
