### ISSUE TITLE
HttpClient needs refactoring

### ISSUE THREAD

**Issue by dnl-blkv** [messagebird/php-rest-api#39]
How to Reproduce
------------------
1. Take a look at https://github.com/messagebird/php-rest-api/blob/master/src/MessageBird/Common/HttpClient.php

What Should Happen
---------------------
1. The code is de-duplicated, clean and easy to understand; each method does exactly and only what it says and does it well

What Happens
--------------
1. Code is a bit challenging to read and contains duplication; some methods do multiple things, or things on multiple levels of abstraction

**Comment by samwierema** [comment]
Hi @dnl-blkv, thanks for opening the issue. 

We don't think this change is needed at this time. There's not a lot of duplication in `HttpClient.php` and the code works well as is. 

We do think there's a few things we can change (e.g. constants for certain things) and maybe some better checks for existence of variables, but the associated PR is too big of a refactor to be merged at this time.

We're going to close the PR for now, but would like to invite you to discuss individual changes you proposed here, and what benefits you see them having over the current code.

**Comment by dnl-blkv** [comment]
@samwierema I can clearly see why you've closed it; probably would have done that myself. In the end, the class is lacking tests (and it is indeed quite hard to test these kind of things). So, it might've also felt a bit like open heart surgery.

The reason I have refactored it was that when I have seen it for the first time as a person who has never seen this code, it seemed a bit complicated. So, I've added comments just to see what can be done. And then it became clear how this should be decomposed! So, I've done it. In the end, it was a good exercise which did not take long.

Of course, this class is not the one which will change most of the time, so the main factor for refactoring it was readability. As you have mentioned, default values, checks for values validity and file paths did benefit more from the refactor because they are more likely to change. The rest just became readable as well-written prose (or so I think) :).

How about applying the changes step by step, in smaller PRs?

As a side note: there is a library in PHP (`php-mock/php-mock-phpunit`) which allows mocking default PHP methods. With proper approach, it would help also with testing the `HttpClient`. As in "whether or not data passed to this curl method was what we were expecting".

**Comment by samwierema** [comment]
@dnl-blkv yes, let's see if and how we can apply changes step by step, in a more digestible manner. I'll leave it to you to propose the steps.

**Comment by chrisminett** [comment]
What about just using a standard package like Guzzle? I don't think there's any need to re-invent an HTTP Client here.

There doesn't appear to be anything bespoke in the existing client itself, and the custom error code handling in `ResponseError` could be easily done in Middleware.

It would also remove the explicit dependency on cURL from this package, as Guzzle defaults to cURL when available, but has compatible fallbacks too.

On top of this, the existing HTTP Client suffers from not re-using connections, which Guzzle does as standard, so there's a potential speed benefit through not renegotiating SSL for every connection.

We've currently written a wrapper to use Guzzle in place of the existing HTTP Client. This has problems due to having to inject the client into the existing code, so it would be nice if it was the default!

**Comment by chrisminett** [comment]
I've tweaked `HttpClient` to use Guzzle. It's not very nice, as this Messagebird package still supports php53, and therefore is limited to Guzzle3.

Also, this maintains the current contracted API for `HttpClient` to avoid BC breaks, however I still feel this could be better achieved by dropping `HttpClient` altogether and simply using Guzzle. That would of course require an increment in the major version number to maintain SemVer, even though `HttpClient` does not form the primary interface of this package.

All-in-all, this can only be an interim solution to the current issues (like #48, #55 and the issue in constructing a new `Messagebird\Client`) but it at least sets out a path to use PHP's de-facto HTTP client rather than re-inventing it, allow connection re-use and (with future Guzzle versions) have afallback alternative to cURL for those that for some reason don't have it available!

See https://github.com/chrisminett/messagebird-php-rest-api/commit/7cfc8fcab7b3f469d6d0dcfa5923b8d3d9d8ea16

**Comment by CoolGoose** [comment]
@chrisminett thank you for the update. We are going to consider using guzzle for the 2.0 release, especially since we dropped support for older php versions.

**Comment by CoolGoose** [comment]
Closing this for now. Although we do want to improve the current situation, pulling in an external dependency is something that we might want to avoid for the time being.

**Comment by chrisminett** [comment]
@CoolGoose While I don't necessarily agree, as dependencies are a great way to use existing solutions to common scenarios, I can appreciate keeping the package as light as possible.

Perhaps as an alternative – to support use cases which are not currently covered (like #48 and #55) – it may be good to look at making the package's own `HttpClient` properly implement the `\Psr\Http\Client\ClientInterface` PSR-18 standard interface for an HTTP Client (and PSR-7 HTTP Message). This could be done in a way that allows implementations of this MessageBird package to _choose_ to provide their own HTTP Client as an alternative to the standard built-in class, so being able to take advantage of features provided by other HTTP clients.
