### ISSUE TITLE
No support for HTTP proxies

### ISSUE THREAD

**Issue by willemstuursma** [messagebird/php-rest-api#48]
We would like to connect to the MessageBird API using an HTTP proxy.

Unfortunately there is no option available to set this.

**Comment by samwierema** [comment]
Hi @willemstuursma, thanks for opening an issue. I think we could potentially add this as an option and to use something like `CURLOPT_PROXY` to manage it. 

We'll review this some more and see if we can change some code soon. Or, should you have the inclination, we'd love to see a pull request.

**Comment by CoonHouse** [comment]
Hello, I managed to successfully post messages to the Messagebird API from behind a proxy. I modified the "performHttpRequest" in "HttpClient.php" to let cUrl use the "CURLOPT_PROXY" option. The problem is that it seems I do not get the same response I would get when using no proxy. The "processRequest" in "Base.php" throws an error because the response is not valid JSON.

> ..../MessageBird/Resources/Base.php:163:Got an invalid JSON response from the server

When i dump the response, I get the following data:

> HTTP/1.1 201 Created
Server: nginx
Date: Fri, 22 Sep 2017 08:00:23 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 674
Connection: keep-alive
Access-Control-Allow-Headers: Authorization, Content-Type
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE
Access-Control-Allow-Credentials: true
Pragma: no-cache
Expires: 0
Cache-Control: must-revalidate, post-check=0, pre-check=0

Any idea how to fix this, or where to search?

Like I said, the messages are successfully posted and also texted to the mobile numbers. I'm only missing the correct response.

**Comment by samwierema** [comment]
@CoonHouse could it be that the proxy is filtering the content when sending back the response? The headers you've sent seem to be good (and it even has `Content-Length`), but the body seems to be missing.

**Comment by Matthijsvdorp** [comment]
@samwierema I can imagine this is not really high on your list but I would like to use it behind a proxy as well. If there was some way to access the CURL handler before doing the requests everyone could just add their own configuration tweaks (i.e. SSL options, proxy, timeouts etc). That will solve more then this issue alone.

**Comment by CoonHouse** [comment]
@Matthijsvdorp, I have this working behind a proxy by modifying the source. I am not at the code right now, so I can not share my solution right now. And i made it work for my situation and did not test all other possible situations that might occur!!  If you are interested, I will look into it and share you my modifications.

Best Regards,

Wilco

**Comment by fas3r** [comment]
Please do. 

Thanks.

**Comment by Matthijsvdorp** [comment]
@CoonHouse I got it working as well but by changing a file in my `vendor/` directory and that feels wrong. Would be nice to have a better solution available. I'll think about and try to PR something.

**Comment by epels** [comment]
Hi @willemstuursma, thanks for opening this issue - version 1.10.0 has just been released and you should now be able to use proxies with the MessageBird client.

HTTP options, and therefore proxies, can be set as follows:

```php
    $httpClient = new HttpClient(Client::endpoint);
    $httpClient->addHttpOption(CURLOPT_PROXY, 'YOUR_PROXY');

    $client = new Client('YOUR_ACCESS_KEY', $httpClient);

    // Do something with $client...
```

Please do not hesitate to let me know if you have any questions about this!
