### ISSUE TITLE
Discontinue support for old PHP versions

### ISSUE THREAD

**Issue by rjelierse** [messagebird/php-rest-api#79]
As you can see from the [list of supported versions](http://php.net/supported-versions.php), most of the versions we're still actively supporting are no longer supported by PHP itself. It might be time to drop support for these versions and update to use language features that are only available on later versions (e.g. type hinting of scalars). Older versions of this package will still be available to those that insist of running on ancient PHP versions, but they would be excluded from new functionality onwards.

**Comment by chrisminett** [comment]
A v2 of this package could achieve so much enhancement, like these PHP versions, a cleaner HTTP client #39 , and making objects immutable.

**Comment by chrisminett** [comment]
It seems that updates to this package are done mainly through contributor PRs - I guess that Messagebird don't use PHP themselves, so there isn't much drive to improve the code quality and get a v2 out.

Perhaps one of the maintainers could create a v2.x branch, so that we might create PRs against that and start getting some improvements in, eg:

* Drop PHP 5.x
* Use Guzzle as the HTTP client rather than re-inventing it
* Remove the mutable objects (everything is public in `Base`, there's no constructor, no validation or validation can be skipped)

**Comment by webmaster777** [comment]
You should use HTTPlug rather than confining to Guzzle. Zee http://httplug.io/

**Comment by webmaster777** [comment]
> A v2 of this package could achieve so much enhancement, like these PHP versions, a cleaner HTTP client #39 , and making objects immutable.

Dropping php version support would not necessarily require a v2 (https://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html)
